name: Build

on:
  pull_request:
    types:
      - "opened"

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  auto-merge-pr:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build

  auto-merge-dependabot-pr:
    name: Auto-merge Dependabot PR
    runs-on: ubuntu-latest
    if: success() || github.event.pull_request.user.login == 'dependabot[bot]' 
    needs: build
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment $PR_URL --body "No issues found, asking Dependabot to merge the pull request."
          gh pr comment $PR_URL --body "@dependabot merge"

  close-dependabot-pr:
    name: Close Dependabot PR
    runs-on: ubuntu-latest
    if: failure() && github.event.pull_request.user.login == 'dependabot[bot]' 
    needs: build
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment $PR_URL --body "Issues found, asking Dependabot to close the pull request & not recreate it again."
          gh pr comment $PR_URL --body "@dependabot close"
 